# Configure sitewide settings
ga_username: ''
gtm_username: ''
url: https://valorem.xyz
permalink: /:title/
timezone: America/New_York # List of time zones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
lang: en-us

# Configure site collections
collections:
  docs:
    permalink: /:collection/:title/
    output: true

# Configure collection defaults
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: general
      image: /assets/images/1-default.jpg
  - scope:
      path: '_docs'
      type: 'docs'
    values:
      layout: doc
      seo:
        type: TechArticle

# Build settings
destination: _site
source: site
include: ['.htaccess', '_redirects']
data_dir: _data
includes_dir: _1-includes
layouts_dir: _2-layouts
keep_files:
  - css
  - assets
kramdown:
  smart_quotes: ['lsquo', 'rsquo', 'ldquo', 'rdquo']
plugins:
  - jekyll-include-cache
  - jekyll-responsive-image
  - jekyll-last-modified-at

# Plugin settings
responsive_image:
  template: _1-includes/partials/image.html
  sizes:
    - width: 100
    - width: 640
    - width: 800
    - width: 1280
  strip: true
  base_path: assets/images
  output_path_format: assets/images/%{dirname}/%{filename}-%{width}.%{extension}
  save_to_source: false
  cache: false